# Generated by Django 4.1.5 on 2023-05-02 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='diametro',
            field=models.CharField(blank=True, default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='independencia',
            field=models.CharField(blank=True, default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='N/A', max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='producto',
            name='respuesta',
            field=models.CharField(blank=True, default='N/A', max_length=400),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='imagen',
            field=models.CharField(max_length=400),
        ),
    ]
