# Generated by Django 4.2 on 2023-05-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_carrito_producto_carrito_productos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id',
        ),
    ]
