# Generated by Django 4.2 on 2023-05-13 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_producto_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('celular', models.IntegerField(max_length=100)),
                ('despacho', models.CharField(max_length=10)),
                ('nombre_calle', models.CharField(max_length=100)),
                ('numero_calle', models.IntegerField(max_length=100)),
                ('tipo_pago', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
