# Generated by Django 4.2 on 2023-05-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_datos_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_compra',
            name='celular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datos_compra',
            name='numero_calle',
            field=models.IntegerField(),
        ),
    ]
