# Generated by Django 4.2 on 2023-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_datos_compra_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_compra',
            name='despacho',
        ),
        migrations.AddField(
            model_name='datos_compra',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_compra',
            name='nombre_calle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datos_compra',
            name='numero_calle',
            field=models.IntegerField(null=True),
        ),
    ]
