# Generated by Django 4.2 on 2023-05-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_datos_compra_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_compra',
            name='region',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
