# Generated by Django 4.2 on 2023-06-18 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productos_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pagado', models.IntegerField()),
                ('estado_pago', models.CharField(max_length=50)),
                ('orden_compra', models.CharField(max_length=50)),
                ('sesion_id', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
                ('codigo_autorizacion', models.CharField(max_length=50)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.datos_compra')),
            ],
        ),
    ]
