# Generated by Django 4.2 on 2023-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_peticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='detalle',
            field=models.TextField(max_length=300),
        ),
    ]
