# Generated by Django 4.2 on 2023-07-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_peticion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='cancelaciones',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='productos_vendidos_mes_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='productos_vendidos_mes_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='total_venta_mes_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='total_venta_mes_2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
