# Generated by Django 4.2 on 2023-07-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_peticion_cancelaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_compra',
            name='estado',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
    ]
