# Generated by Django 4.2 on 2023-07-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_datos_compra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_compra',
            name='estado',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
