# Generated by Django 4.2 on 2023-07-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_datos_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_compra',
            name='enviado',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datos_compra',
            name='validacion',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_compra',
            name='estado',
            field=models.CharField(default='N/A', max_length=50, null=True),
        ),
    ]
