# Generated by Django 4.2 on 2023-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_datos_compra_enviado_datos_compra_validacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombreCategoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='desempeño',
            field=models.CharField(default='N/A', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='peticion',
            name='detalle',
            field=models.TextField(max_length=800),
        ),
    ]
